openapi: 3.0.0
info:
  title: PRD API
  version: 1.0.0
paths:
  /prds:
    get:
      summary: Get all PRDs
      responses:
        '200':
          description: A list of PRDs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PRD'
    post:
      summary: Create a new PRD
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PRD'
      responses:
        '201':
          description: The created PRD
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PRD'
  /prds/{id}:
    get:
      summary: Get a PRD by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The PRD
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PRD'
        '404':
          description: PRD not found
    put:
      summary: Update a PRD by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PRD'
      responses:
        '200':
          description: The updated PRD
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PRD'
        '404':
          description: PRD not found
    delete:
      summary: Delete a PRD by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content
        '404':
          description: PRD not found
components:
  schemas:
    PRD:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time