openapi: 3.0.0
info:
  title: PRD API
  version: 1.0.0
paths:
  /prds:
    get:
      summary: Get all PRDs
      responses:
        "200":
          description: A list of PRDs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PRD"
    post:
      summary: Create a new PRD
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PRD"
      responses:
        "201":
          description: The created PRD
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PRD"
  /prds/{id}:
    get:
      summary: Get a PRD by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The PRD
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PRD"
        "404":
          description: PRD not found
    put:
      summary: Update a PRD by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PRD"
      responses:
        "200":
          description: The updated PRD
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PRD"
        "404":
          description: PRD not found
    delete:
      summary: Delete a PRD by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: No content
        "404":
          description: PRD not found
  /prds/{id}/generate:
    post:
      summary: Generate AI content for a PRD
      description: Generate content for a specific section of a PRD or enhance existing content using AI
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the PRD to generate content for
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GenerateContentRequest"
      responses:
        "200":
          description: Successfully generated content
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenerateContentResponse"
        "400":
          description: Bad request - invalid input parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: PRD not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error - AI generation failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /prds/{id}/critique:
    post:
      summary: Get AI critique and feedback for a PRD
      description: Analyze an existing PRD and provide detailed critique, suggestions, and improvement recommendations
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the PRD to critique
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CritiqueRequest"
      responses:
        "200":
          description: Successfully generated critique
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CritiqueResponse"
        "400":
          description: Bad request - invalid input parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: PRD not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error - AI critique failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    PRD:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    GenerateContentRequest:
      type: object
      required:
        - prompt
      properties:
        prompt:
          type: string
          description: The prompt or instruction for AI content generation
          example: "Generate a detailed user story for mobile app login feature"
        context:
          type: string
          description: Additional context to help with content generation
          example: "This is for a B2B SaaS application with enterprise security requirements"
        tone:
          type: string
          enum: ["professional", "casual", "technical", "executive"]
          default: "professional"
          description: The tone to use for generated content
        length:
          type: string
          enum: ["brief", "standard", "detailed", "comprehensive"]
          default: "standard"
          description: The desired length/detail level of generated content
        existing_content:
          description: Existing content to enhance or build upon
        conversation_history:
          type: array
          items:
            $ref: "#/components/schemas/ConversationMessage"
          description: Previous conversation messages for interactive sessions
    CritiqueRequest:
      type: object
      properties:
        focus_areas:
          type: array
          items:
            type: string
            enum:
              [
                "completeness",
                "clarity",
                "structure",
                "feasibility",
                "requirements",
                "user_experience",
                "technical",
                "business_value",
              ]
          description: Specific areas to focus the critique on
          example: ["completeness", "clarity", "requirements"]
        depth:
          type: string
          enum: ["overview", "detailed", "comprehensive"]
          default: "detailed"
          description: How detailed the critique should be
        include_suggestions:
          type: boolean
          default: true
          description: Whether to include specific improvement suggestions
        custom_criteria:
          type: string
          description: Any custom criteria or specific aspects to evaluate
          example: "Focus on security requirements and compliance considerations"
    ConversationMessage:
      type: object
      required:
        - role
        - content
      properties:
        role:
          type: string
          enum: ["user", "assistant"]
          description: The role of the message sender
        content:
          type: string
          description: The message content
        timestamp:
          type: string
          format: date-time
          description: When the message was sent
    GenerateContentResponse:
      type: object
      properties:
        generated_content:
          type: string
          description: The AI-generated content
        tokens_used:
          type: integer
          description: Number of tokens consumed in the generation
        model_used:
          type: string
          description: The AI model used for generation
          example: "gpt-4"
        generation_time:
          type: number
          format: float
          description: Time taken to generate content in seconds
        suggestions:
          type: array
          items:
            type: string
          description: Additional suggestions for improving the content
    CritiqueResponse:
      type: object
      properties:
        overall_score:
          type: number
          format: float
          minimum: 0
          maximum: 10
          description: Overall quality score for the PRD (0-10)
        strengths:
          type: array
          items:
            type: string
          description: Areas where the PRD excels
        weaknesses:
          type: array
          items:
            type: string
          description: Areas that need improvement
        missing_sections:
          type: array
          items:
            type: string
          description: Important sections that are missing from the PRD
        suggestions:
          type: array
          items:
            $ref: "#/components/schemas/CritiqueSuggestion"
          description: Specific improvement suggestions
        detailed_feedback:
          type: object
          additionalProperties:
            type: string
          description: Section-by-section detailed feedback
        action_items:
          type: array
          items:
            type: string
          description: Prioritized list of actions to improve the PRD
        critique_summary:
          type: string
          description: Executive summary of the critique
    CritiqueSuggestion:
      type: object
      properties:
        category:
          type: string
          enum:
            [
              "structure",
              "content",
              "clarity",
              "requirements",
              "technical",
              "business",
            ]
          description: Category of the suggestion
        priority:
          type: string
          enum: ["high", "medium", "low"]
          description: Priority level of the suggestion
        title:
          type: string
          description: Brief title of the suggestion
        description:
          type: string
          description: Detailed description of the suggestion
        example:
          type: string
          description: Example of how to implement the suggestion
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message describing what went wrong
        code:
          type: string
          description: Error code for programmatic handling
        details:
          type: object
          description: Additional error details
